server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    session:
      timeout: 60m

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  web:
#    resources:
#      static-locations: classpath:/resource/static/**

